### ISSUE TITLE
Multi-service support

### ISSUE THREAD

**Issue by aquiladev** [aquiladev/ipfs-action#1]
Would be good to have multi-service support (infura, pinata, fission, IPFS cluster, DAppNode) besides default and custom endpoint. 
Take a look https://www.npmjs.com/package/ipfs-deploy

**Comment by aquiladev** [comment]
https://github.com/aquiladev/ipfs-action/commit/a5bcaecb8248f4d614b777e12f310df52a246790 Pinata service support

**Comment by markg85** [comment]
Perhaps related, i'd very much like to pin it to multiple services in one script. So in my case to a IPFS node i'm running and to pinata.

**Comment by aquiladev** [comment]
@markg85 The issue is not related to simultaneous multi-service support. I think it is quite a rear case.
You can solve it with multiple steps in your pipeline yaml.
Something like:
```
    - name: Upload to IPFS
      uses: aquiladev/ipfs-action@v0.1.3
      with:
        path: ./build

    - name: Upload to Pinata
      uses: aquiladev/ipfs-action@v0.1.3
      with:
        path: ./build
        service: pinata
        pinataKey: ${{ secrets.PINATA_KEY }}
        pinataSecret: ${{ secrets.PINATA_SECRET }}
```
