### ISSUE TITLE
Pin to 'Infura IPFS' project

### ISSUE THREAD

**Issue by ss-o** [aquiladev/ipfs-action#21]
Hi,

Could you advise on the difference between a regular Infura IPFS pin and a pin to a personal Infura IPFS project? 

I planned to do something similar to:

```yaml
uses: aquiladev/ipfs-action@v1
with:
  path: ./build
  service: infura
  pinataKey: ${{ secrets.PROJECT_ID }}
  pinataSecret: ${{ secrets.PROJECT_SECRET }}
```

But got confused as unable to find info on differences (limits, sizes, etc.). Does it worth pinning to the personal project?

**Comment by aquiladev** [comment]
You misconfigured the action a bit, it might be the reason of wrong understanding.

**Infura** does not require any keys or secrets. You can use it for free/unauthorized
**Pinata** does require key and secret, you need to register a user in pinata service in order to use it.
In your configuration you choose `infura` service with `pinata` parameters. In the case parameters will be ignored.

it is the same as 
```
uses: aquiladev/ipfs-action@v1
with:
  path: ./build
  service: infura
```
