### ISSUE TITLE
Getting "The user aborted a request."

### ISSUE THREAD

**Issue by etienne-napoleone** [aquiladev/ipfs-action#31]
Hello,

While trying to use the plugin with multiple configurations, including:

```yml
name: Upload illustration to IPFS

on:
  push:
    paths:
      - assets/illustration.png

jobs:
  upload:
    name: Upload
    runs-on: ubuntu-latest
    steps:
      - uses: aquiladev/ipfs-action@v0.2.0
        with:
          path: assets/
```

```yml
name: Upload illustration to IPFS

on:
  push:
    paths:
      - assets/illustration.png

jobs:
  upload:
    name: Upload
    runs-on: ubuntu-latest
    steps:
      - uses: aquiladev/ipfs-action@v0.2.0
        with:
          path: assets/
          host: cf-ipfs.com
          port: 443
          protocol: https
          timeout: 180000
          verbose: true
```

and the same ones using a file `path` instead of directory, and also using v0.1.3

The result is always:

```
Run aquiladev/ipfs-action@v0.2.0
  with:
    path: assets/illustration.png
    service: ipfs
    timeout: 60000
    verbose: false
    host: ipfs.komputing.org
    port: 443
    protocol: https
    headers: {}
Error: The user aborted a request.
(node:1510) UnhandledPromiseRejectionWarning: AbortError: The user aborted a request.
    at abort (/home/runner/work/_actions/aquiladev/ipfs-action/v0.2.0/node_modules/node-fetch/lib/index.js:1418:16)
    at AbortSignal.abortAndFinalize (/home/runner/work/_actions/aquiladev/ipfs-action/v0.2.0/node_modules/node-fetch/lib/index.js:1433:4)
    at AbortSignal.dispatchEvent (/home/runner/work/_actions/aquiladev/ipfs-action/v0.2.0/node_modules/event-target-shim/dist/event-target-shim.js:818:35)
    at abortSignal (/home/runner/work/_actions/aquiladev/ipfs-action/v0.2.0/node_modules/abort-controller/dist/abort-controller.js:52:12)
    at AbortController.abort (/home/runner/work/_actions/aquiladev/ipfs-action/v0.2.0/node_modules/abort-controller/dist/abort-controller.js:91:9)
    at AbortSignal.onAbort (/home/runner/work/_actions/aquiladev/ipfs-action/v0.2.0/node_modules/any-signal/index.js:13:16)
    at AbortSignal.dispatchEvent (/home/runner/work/_actions/aquiladev/ipfs-action/v0.2.0/node_modules/event-target-shim/dist/event-target-shim.js:818:35)
    at abortSignal (/home/runner/work/_actions/aquiladev/ipfs-action/v0.2.0/node_modules/abort-controller/dist/abort-controller.js:52:12)
    at AbortController.abort (/home/runner/work/_actions/aquiladev/ipfs-action/v0.2.0/node_modules/abort-controller/dist/abort-controller.js:91:9)
    at AbortSignal.onAbort (/home/runner/work/_actions/aquiladev/ipfs-action/v0.2.0/node_modules/any-signal/index.js:13:16)
(node:1510) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1510) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
