### ISSUE TITLE
Cannot call a class as a function

### ISSUE THREAD

**Issue by Filicipa** [aquiladev/ipfs-action#79]
Hello, i tried use worklow for upload files to Pinata and getting error. Could you help me to resolve? 
PINATA_KEY = `API Key` 
PINATA_SECRET = `API Secret`
getting from Pinata API Key Info

I didn't use `JWT (Secret access token)`
```
Error: Cannot call a class as a function
/home/runner/work/_actions/aquiladev/ipfs-action/master/dist/index.js:41598
    throw new TypeError("Cannot call a class as a function");
          ^

TypeError: Cannot call a class as a function
    at _classCallCheck (/home/runner/work/_actions/aquiladev/ipfs-action/master/dist/index.js:41598:11)
    at PinataClient (/home/runner/work/_actions/aquiladev/ipfs-action/master/dist/index.js:65499:37)
    at builder (/home/runner/work/_actions/aquiladev/ipfs-action/master/dist/index.js:130790:12)
    at Object.pinata (/home/runner/work/_actions/aquiladev/ipfs-action/master/dist/index.js:130737:23)
    at Object.upload (/home/runner/work/_actions/aquiladev/ipfs-action/master/dist/index.js:130910:[39](https://github.com/woof-compound/dapp/actions/runs/11594824265/job/32282208805#step:3:40))
    at run (/home/runner/work/_actions/aquiladev/ipfs-action/master/dist/index.js:130871:35)
    at /home/runner/work/_actions/aquiladev/ipfs-action/master/dist/index.js:135618:1
    at /home/runner/work/_actions/aquiladev/ipfs-action/master/dist/index.js:135619:3
    at Object.<anonymous> (/home/runner/work/_actions/aquiladev/ipfs-action/master/dist/index.js:135622:12)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)

Node.js v20.13.1
##[debug]Node Action run completed with exit code 1
##[debug]Finishing: Deploy IPFS
```

Thats part of my workflow for testing
```yaml
      - name: Generate file
        run: |
          mkdir build
          echo "Hello Pintata!!!" > index.html

      - name: Deploy IPFS
        uses: aquiladev/ipfs-action@master
        with:
          path: ./build
          service: pinata
          pinataKey: ${{ secrets.PINATA_KEY }}
          pinataSecret: ${{ secrets.PINATA_SECRET }}
```
